#!/usr/bin/env python3
# Created by: Patrick
# Created on: 11/26/2025
# calculates the GCF of two numbers using the Euclidean Algorithm

def main():
    print("This program will calculate the (GCF) of two numbers.")

    try:
        # Ask user for two numbers
        num1 = int(input("Enter the first number: "))
        num2 = int(input("Enter the second number: "))

        # Check for positive integers
        if num1 <= 0 or num2 <= 0:
            print("Please enter positive integers only.")
        else:
        # Calculates GCF using the Euclidean Algorithm
            a = num1
            b = num2

        # While b is not equal to 0
            while b != 0:

        # temp = a divided by b
                temp = a % b
                a = b
                b = temp

        # Display the GCF
            print(f"The Greatest Common Factor of {num1} and {num2} is: {a}")

        # Handles invalid input
    except ValueError:
        print("Invalid input. Please enter valid integers.")

if __name__ == "__main__":
    main()
